server:
  port: 9090
  servlet:
    context-path: /
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?serverTime=Asia/Seoul
    username: ten
    password: 1q2w3e4r5t!
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true        

  jackson:
    serialization:
      fail-on-empty-beans: false

kakao:
  key: f3a668adf71308ab55866383b677a93bdabfc269f1cd2caec6e37a8f41b13cfe7728cf4d14579ce742bd9823d6c0678a692eea4d722d8214dbf24db808a78cb6